In [3]:
a = [[1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12],
    [13,14,15],
    [16,17,18]]

In [4]:
import pandas as pd

In [5]:
data = pd.DataFrame(a,columns=['a','b','c'])

In [6]:
data

a   b   c
0   1   2   3
1   4   5   6
2   7   8   9
3  10  11  12
4  13  14  15
5  16  17  18

In [21]:
import numpy as np

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM

# Input sequence
wholeSequence = [[0,0,0,0,0,0,0,0,0,2,1],
                 [0,0,0,0,0,0,0,0,2,1,0],
                 [0,0,0,0,0,0,0,2,1,0,0],
                 [0,0,0,0,0,0,2,1,0,0,0],
                 [0,0,0,0,0,2,1,0,0,0,0],
                 [0,0,0,0,2,1,0,0,0,0,0],
                 [0,0,0,2,1,0,0,0,0,0,0],
                 [0,0,2,1,0,0,0,0,0,0,0],
                 [0,2,1,0,0,0,0,0,0,0,0],
                 [2,1,0,0,0,0,0,0,0,0,0],
                [0,0,0,0,0,0,0,0,0,3,1],
                 [0,0,0,0,0,0,0,0,3,1,0],
                 [0,0,0,0,0,0,0,3,1,0,0],
                 [0,0,0,0,0,0,3,1,0,0,0],
                 [0,0,0,0,0,3,1,0,0,0,0],
                 [0,0,0,0,3,1,0,0,0,0,0],
                 [0,0,0,3,1,0,0,0,0,0,0],
                 [0,0,3,1,0,0,0,0,0,0,0],
                 [0,3,1,0,0,0,0,0,0,0,0],
                 [3,1,0,0,0,0,0,0,0,0,0]]

# Preprocess Data:
wholeSequence = np.array(wholeSequence, dtype=float) # Convert to NP array.
data = wholeSequence[:-1] # all but last
target = wholeSequence[1:] # all but first


In [22]:
wholeSequence[:-1]

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  3.,  1.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  3.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  3.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  3.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  3.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  3.,  1.,  0

In [24]:
for i,val in enumerate(data):
    print(val)
    print("TARGER")
    print(target[i])
# Reshape training data for Keras LSTM model
# The training data needs to be (batchIndex, timeStepIndex, dimentionIndex)
# Single batch, 9 time steps, 11 dimentions
data = data.reshape((2, 9, 11))
target = target.reshape((1, 9, 11))

# Build Model
model = Sequential()  
model.add(LSTM(11, input_shape=(9, 11), unroll=True, return_sequences=True))
model.add(Dense(11))
model.compile(loss='mean_absolute_error', optimizer='adam')
model.fit(data, target, nb_epoch=2000, batch_size=1, verbose=10)


[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  2.  1.]
TARGER
[ 0.  0.  0.  0.  0.  0.  0.  0.  2.  1.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  0.  2.  1.  0.]
TARGER
[ 0.  0.  0.  0.  0.  0.  0.  2.  1.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  0.  2.  1.  0.  0.]
TARGER
[ 0.  0.  0.  0.  0.  0.  2.  1.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  0.  2.  1.  0.  0.  0.]
TARGER
[ 0.  0.  0.  0.  0.  2.  1.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  0.  2.  1.  0.  0.  0.  0.]
TARGER
[ 0.  0.  0.  0.  2.  1.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  0.  2.  1.  0.  0.  0.  0.  0.]
TARGER
[ 0.  0.  0.  2.  1.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  0.  2.  1.  0.  0.  0.  0.  0.  0.]
TARGER
[ 0.  0.  2.  1.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  2.  1.  0.  0.  0.  0.  0.  0.  0.]
TARGER
[ 0.  2.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  2.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
TARGER
[ 2.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 2.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
TARGER
[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  3.  1.]
[ 0.  0.  

ValueError: total size of new array must be unchanged

In [10]:
data

array([[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]])

In [11]:
target

array([[[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 0.,  2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
        [ 2.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]]])

In [20]:
#test = np.array([0.,  0.,  0.,  0.,  0.,  0.,  2.,  1.,  0.,  0.,  0.]).reshape(1,1,11)
#print (test)
model.predict(data)

array([[[  2.62141228e-04,   7.00205564e-04,  -3.26804817e-04,
          -2.05848366e-04,   4.65136021e-04,   1.25348568e-04,
          -7.05599785e-04,  -9.10550356e-04,   1.99991369e+00,
           1.00014377e+00,  -4.70910221e-04],
        [  3.49998474e-04,   2.01821327e-03,  -1.48685277e-03,
          -8.78487714e-04,   1.37912855e-03,  -1.25610083e-03,
           6.37508929e-05,   1.99937773e+00,   1.00118637e+00,
           9.44331288e-04,  -8.30728561e-04],
        [ -2.19970942e-04,   6.21765852e-04,   6.02751970e-06,
          -1.26070809e-03,   1.05056167e-03,  -9.62037593e-04,
           2.00056291e+00,   9.99927938e-01,   1.04707479e-03,
           1.02618337e-03,  -2.32324004e-04],
        [  6.31302595e-04,   1.08912587e-03,  -1.24078244e-04,
           1.87197700e-04,   1.36017054e-03,   1.99862194e+00,
           9.99378800e-01,  -5.56468964e-04,   1.68025494e-04,
          -8.30471516e-04,  -3.69451940e-04],
        [  1.33126974e-04,  -6.72191381e-04,   2.61317939e-0